name: checks

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  check:
    concurrency:
      cancel-in-progress: ${{ github.ref_name != 'main' }}
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}

    name: Lint, build & check exports
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          cache: true

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*

      - name: Use Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: 2.x

      - name: Install dependencies
        run: pnpm install

      - name: Biome
        run: pnpm biome ci

      - name: Lint for deno/jsr
        run: pnpm lint:deno

      - name: Build
        run: pnpm build
